# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='comments',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
